#Makes and cleans subdirectories
#at the command prompt
#make
#make clean

serverClient:
	cd 3761_Lab2_client; make
	cd 3761_Lab2_server; make
clean:
	cd 3761_Lab2_client; make clean
	cd 3761_Lab2_server; make clean